



#### 1、rpc错误处理

按照正常情况下，go-zero的rpc服务是基于grpc的，默认返回的错误是grpc的status.Error 没法给我们自定义的错误合并，
并且也不适合自定义的错误，它的错误码、错误类型都是定义死在grpc包中的

grpc的status.Error的code：

```go
// A Code is an unsigned 32-bit error code as defined in the gRPC spec.
type Code uint32
.......
```

grpc的err对应的错误码其实就是一个uint32 ， 自定义错误用uint32然后在rpc的全局拦截器返回时候转成grpc的err

errCode.go

```go
package errx

//成功返回
const OK uint32 = 200

/**(前3位代表业务,后三位代表具体功能)**/

//全局错误码
const SERVER_COMMON_ERROR uint32 = 100001
const REUQEST_PARAM_ERROR uint32 = 100002
const TOKEN_EXPIRE_ERROR uint32 = 100003
const TOKEN_GENERATE_ERROR uint32 = 100004
const DB_ERROR uint32 = 100005

//用户模块
```

errMsg.go

```go
package errx

var message map[uint32]string

func init() {
   message = make(map[uint32]string)
   message[OK] = "SUCCESS"
   message[SERVER_COMMON_ERROR] = "服务器开小差啦,稍后再来试一试"
   message[REUQEST_PARAM_ERROR] = "参数错误"
   message[TOKEN_EXPIRE_ERROR] = "token失效，请重新登陆"
   message[TOKEN_GENERATE_ERROR] = "生成token失败"
   message[DB_ERROR] = "数据库繁忙,请稍后再试"
}

func MapErrMsg(errcode uint32) string {
   if msg, ok := message[errcode]; ok {
      return msg
   } else {
      return "服务器开小差啦,稍后再来试一试"
   }
}

func IsCodeErr(errcode uint32) bool {
   if _, ok := message[errcode]; ok {
      return true
   } else {
      return false
   }
}
```

errors.go

```go
package errx

import (
   "fmt"
)

/**
常用通用固定错误
*/

type CodeError struct {
   errCode uint32
   errMsg  string
}

//返回给前端的错误码
func (e *CodeError) GetErrCode() uint32 {
   return e.errCode
}

//返回给前端显示端错误信息
func (e *CodeError) GetErrMsg() string {
   return e.errMsg
}

func (e *CodeError) Error() string {
   return fmt.Sprintf("ErrCode:%d，ErrMsg:%s", e.errCode, e.errMsg)
}

func NewErrCodeMsg(errCode uint32, errMsg string) *CodeError {
   return &CodeError{errCode: errCode, errMsg: errMsg}
}
func NewErrCode(errCode uint32) *CodeError {
   return &CodeError{errCode: errCode, errMsg: MapErrMsg(errCode)}
}

func NewErrMsg(errMsg string) *CodeError {
   return &CodeError{errCode: SERVER_COMMON_ERROR, errMsg: errMsg}
}
```



比如我们在用户注册时候的rpc代码

```go

var ErrUserAlreadyRegisterError = errx.NewErrMsg("用户已注册")

func NewRegisterLogic(ctx context.Context, svcCtx *svc.ServiceContext) *RegisterLogic {
    return &RegisterLogic{
        ctx:    ctx,
        svcCtx: svcCtx,
        Logger: logx.WithContext(ctx),
    }
}

func (l *RegisterLogic) Register(in *pb.RegisterReq) (*pb.RegisterResp, error) {
    //1、检验验证码
    verifyCaptchaResp, err := NewVerifyCaptchaLogic(l.ctx, l.svcCtx).VerifyCaptcha(&pb.VerifyCaptchaReq{Uuid: in.Uuid, Answer: in.Code, Clear: true})
    if err != nil {
        return nil, errors.Wrapf(errx.NewErrCode(errx.SERVER_COMMON_ERROR), "req: %+v", in)
    }
    if !verifyCaptchaResp.Success {
        return nil, errors.Wrapf(ErrCaptchaIncorrectError, "captcha verify failed, input code:%s", in.Code)
    }

	//2、根据类型查重 1:用户名 2:邮箱
	expr := l.svcCtx.Query.User.Username.Eq(in.Key)
	if in.Type == globalkey.RegisterType_Email {
		expr = l.svcCtx.Query.User.Email.Eq(in.Key)
	}
	user, err := l.svcCtx.Query.User.WithContext(l.ctx).Where(expr).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, errors.Wrapf(errx.NewErrCode(errx.DB_ERROR), "Register db user find user err:%v,user:%+v", err, user)
	}

	if user != nil {
		//用户名或邮箱存在
		return nil, errors.Wrapf(ErrUserAlreadyRegisterError, "Register user exist:user:%+v", user)
	}
	u := new(model.User)
	u.Username = in.Key

	if in.Type == globalkey.RegisterType_Email {
		u.Email = in.Key
		u.Username = shortuuid.New()
	}

	if len(in.Password) > 0 {
		hashAndSalt, err := auth.HashAndSalt(in.Password)
		if err != nil {
			return nil, errors.Wrapf(errx.NewErrCode(errx.SERVER_COMMON_ERROR), "Register user hashAndSalt err:%v,user:%+v", err, user)
		}
		u.Password = hashAndSalt
	}

	if err := l.svcCtx.Query.User.WithContext(l.ctx).Create(u); err != nil {
		return nil, errors.Wrapf(errx.NewErrCode(errx.DB_ERROR), "Register db user create user err:%v,user:%+v", err, user)
	}

	//2、生成token
	generateTokenLogic := NewGenerateTokenLogic(l.ctx, l.svcCtx)

	tokenResp, err := generateTokenLogic.GenerateToken(&usercenter.GenerateTokenReq{
		UserId: u.ID,
	})
	if err != nil {
		return nil, errors.Wrapf(ErrGenerateTokenError, "GenerateToken userId : %d", u.ID)
	}

	return &usercenter.RegisterResp{
		Token:   tokenResp.Token,
		Expire:  tokenResp.Expire,
		Refresh: tokenResp.Refresh,
	}, nil
}
```


```go
errors.Wrapf(ErrUserAlreadyRegisterError, "Register user exist:user:%+v", user)
```

第一个参数， ErrUserAlreadyRegisterError 定义在上方 就是使用errx.NewErrMsg("用户已注册") ， 返回给前端友好的提示。

第二个参数，就是记录在服务器日志，可以写详细一点都没关系只会记录在服务器不会被返回给前端


⚠️【注】在rpc的启动Run方法中，加了grpc的全局拦截器，这个很重要 ，如果不加这个没办法实现

```go

func Run() {
	........
	//rpc log,grpc的全局拦截器
	s.AddUnaryInterceptors(rpcserver.LoggerInterceptor)
	.......
}
```

rpcserver.LoggerInterceptor的具体实现

```go
import(
		...
  	"github.com/pkg/errors"
)

func LoggerInterceptor(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (resp interface{}, err error) {

   resp, err = handler(ctx, req)
   if err != nil {
      causeErr := errors.Cause(err)                // err类型
      if e, ok := causeErr.(*xerr.CodeError); ok { //自定义错误类型
         logx.WithContext(ctx).Errorf("【RPC-SRV-ERR】 %+v", err)

         //转成grpc err
         err = status.Error(codes.Code(e.GetErrCode()), e.GetErrMsg())
      } else {
         logx.WithContext(ctx).Errorf("【RPC-SRV-ERR】 %+v", err)
      }

   }

   return resp, err
}
```

当有请求进入到rpc服务时候，先进入拦截器然后就是执行handler方法，

因为grpc内部业务在返回错误时候

1）如果是业务错误，会统一用errx生成错误，这样就可以拿到定义的错误信息，在这里统一转成  grpc错误err = status.Error(codes.Code(e.GetErrCode()), e.GetErrMsg())，
那这里获取到的，e.GetErrCode()就是定义的code，e.GetErrMsg() 就是之前定义返回的错误第二个参数

2）但是还有一种情况是rpc服务异常了底部抛出来的错误，本身就是grpc错误了，那这种的直接就记录异常就好了



#### 3、api错误

当api在logic中调用rpc的Register时候，rpc返回了上面的错误信息:

```go
......
func (l *RegisterLogic) Register(req *types.RegisterReq) (*types.RegisterResp, error) {

    registerResp, err := l.svcCtx.UsercenterRpc.Register(l.ctx, &pb.RegisterReq{
        Type:     req.Type,
        Key:      req.Key,
        Password: req.Password,
        Code:     req.Code,
        Uuid:     req.Uuid,
    })
    if err != nil {
        return nil, errors.Wrapf(err, "req: %+v", req)
    }
    
    var resp types.RegisterResp
    _ = copier.Copy(&resp, registerResp)
    
    return &resp, nil
}
```



这里同样是使用标准包的errors.Wrapf ， 也就是说所有业务中返回错误都使用标准包的errors，但是内部参数要使用errx定义的错误

这里有2个注意点

1）api服务想把rpc返回给前端友好的错误提示信息，想直接返回给前端不做任何处理（比如rpc已经返回了“用户已注册”，api不想做什么处理，就想把这个错误信息直接返回给前端）

针对这种情况，将rpc调用处的err直接作为errors.Wrapf 第一个参数扔出去，但是第二个参数最好记录一下自己需要的详细日志方便后续在api中国呢查看

2）api服务不管rpc返回的是什么错误信息，在api重新定义给前端返回错误信息（比如rpc已经返回了“用户已注册”，api想调用rpc时只要有错误我就返回给前端“用户注册失败”）

针对这种情况，第一个参数使用errx重新定义一个错误即可:

```go
func (l *RegisterLogic) Register(req types.RegisterReq) (*types.RegisterResp, error) {
	.......
	if err != nil {
		return nil, errors.Wrapf(errx.NewErrMsg("用户注册失败"), "req: %+v,rpc err:%+v", req,err)
	}
	.....
}

```



最终返回给前端是在handler中处理的：

```go
func RegisterHandler(ctx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.RegisterReq
		if err := httpx.Parse(r, &req); err != nil {
			result.ParamErrorResult(r, w, err)
			return
		}

		l := user.NewRegisterLogic(r.Context(), ctx)
		resp, err := l.Register(req)
		result.HttpResult(r, w, resp, err)
	}
}
```


在core/result/httpResult.go中

【注】每次使用goctl都要手动改太麻烦，可以使用go-zero给提供的template模版功能，修改一下handler生成模版即可



ParamErrorResult专门处理参数错误

```
//http 参数错误返回
func ParamErrorResult(r *http.Request, w http.ResponseWriter, err error) {
   errMsg := fmt.Sprintf("%s ,%s", errx.MapErrMsg(errx.REUQEST_PARAM_ERROR), err.Error())
   httpx.WriteJson(w, http.StatusBadRequest, Error(errx.REUQEST_PARAM_ERROR, errMsg))
}
```

HttpResult，业务返回的错误处理：

```go

//http返回
func HttpResult(r *http.Request, w http.ResponseWriter, resp interface{}, err error) {

	if err == nil {
		//成功返回
		r := Success(resp)
		httpx.WriteJson(w, http.StatusOK, r)
	} else {
		//错误返回
		errcode := errx.SERVER_COMMON_ERROR
		errmsg := "服务器开小差啦，稍后再来试一试"

		causeErr := errors.Cause(err)                // err类型
		if e, ok := causeErr.(*errx.CodeError); ok { //自定义错误类型
			//自定义CodeError
			errcode = e.GetErrCode()
			errmsg = e.GetErrMsg()
		} else {
			if gstatus, ok := status.FromError(causeErr); ok { // grpc err错误
				grpcCode := uint32(gstatus.Code())
				if errx.IsCodeErr(grpcCode) { //区分自定义错误跟系统底层、db等错误，底层、db错误不能返回给前端
					errcode = grpcCode
					errmsg = gstatus.Message()
				}
			}
		}

		logx.WithContext(r.Context()).Errorf("【API-ERR】 : %+v ", err)

		httpx.WriteJson(w, http.StatusBadRequest, Error(errcode, errmsg))
	}
}
```



err ： 要记录的日志错误

errcode ： 返回给前端的错误码

errmsg ：返回给前端的友好的错误提示信息

成功直接返回，如果遇到错误了，也是使用github.com/pkg/errors这个包判断错误 是自定义的错误（api中定义的错误直接使用自定义的errx），还是grpc错误（rpc业务抛出来的），
如果是grpc错误再通过uint32转成自定义的错误码，根据错误码再去自定义错误信息中找到定义的错误信息返回给前端，
如果是api错误直接返回给前端自定义的错误信息，
都找不到那就返回默认错误“服务器开小差了” ,

